# Auto-generated by generate_models.sh. Do not edit by hand.
"""Provenance metadata for the generated schema models."""

UCP_SCHEMA_REF = "c5c61396ebf9a5afb9c4169bfa3af1409daa6fd6"
"""Commit SHA on Universal-Commerce-Protocol/ucp the models were generated from."""

GENERATE_COMMAND = "generate_models.sh --ref c5c61396ebf9a5afb9c4169bfa3af1409daa6fd6"
"""The generate_models.sh invocation that produced the current tree."""
