#!/bin/bash
# Generate Pydantic models from UCP JSON Schemas

# Ensure we are in the script's directory
cd "$(dirname "$0")" || exit

# Add ~/.local/bin to PATH for uv
export PATH="$HOME/.local/bin:$PATH"

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "Error: git not found. Please install git."
    exit 1
fi

# UCP source selection — three modes:
#   ./generate_models.sh                  # main branch
#   ./generate_models.sh 2026-04-08       # release/2026-04-08 branch
#   ./generate_models.sh --ref <sha|ref>  # arbitrary commit/branch/tag
#
# Identity-linking, info_code, and warning_code schemas merged after the
# 2026-04-08 release branch was cut, so consumers needing those must pin
# an explicit ref via --ref.
REF_MODE=""
REF_VALUE=""
if [ "$1" = "--ref" ]; then
    if [ -z "$2" ]; then
        echo "Error: --ref requires a commit SHA, branch, or tag." >&2
        exit 1
    fi
    REF_MODE="ref"
    REF_VALUE="$2"
    echo "Cloning ucp at ref $REF_VALUE..."
elif [ -z "$1" ]; then
    REF_MODE="branch"
    REF_VALUE="main"
    echo "No version specified, cloning main branch..."
else
    REF_MODE="branch"
    REF_VALUE="release/$1"
    echo "Cloning version $1 (branch: $REF_VALUE)..."
fi

# Ensure ucp directory is clean before cloning
rm -rf ucp
if [ "$REF_MODE" = "ref" ]; then
    # Arbitrary ref may not be reachable via shallow clone of a branch;
    # do a full clone then check out the ref.
    git clone https://github.com/Universal-Commerce-Protocol/ucp ucp
    (cd ucp && git checkout "$REF_VALUE")
else
    git clone -b "$REF_VALUE" --depth 1 https://github.com/Universal-Commerce-Protocol/ucp ucp
fi

# Resolve the actual commit SHA we ended up on (for provenance manifest below)
UCP_SCHEMA_REF="$(cd ucp && git rev-parse HEAD)"
echo "ucp HEAD: $UCP_SCHEMA_REF"

# Output directory
OUTPUT_DIR="src/ucp_sdk/models/schemas"

# Schema directory (relative to this script)
SCHEMA_DIR="ucp/source/schemas"

echo "Preprocessing schemas..."
uv run python preprocess_schemas.py

echo "Generating Pydantic models from preprocessed schemas..."

# Check if uv is installed
if ! command -v uv &> /dev/null; then
    echo "Error: uv not found."
    echo "Please install uv: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

# Ensure output directory is clean
rm -r -f "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"


# Run generation using uv
# We use --use-schema-description to use descriptions from JSON schema as docstrings
# We use --field-constraints to include validation constraints (regex, min/max, etc.)
# Note: Formatting is done as a post-processing step.
uv run \
    --link-mode=copy \
    --extra-index-url https://pypi.org/simple python \
    -m datamodel_code_generator \
    --input "$SCHEMA_DIR" \
    --input-file-type jsonschema \
    --output "$OUTPUT_DIR" \
    --output-model-type pydantic_v2.BaseModel \
    --use-schema-description \
    --field-constraints \
    --use-field-description \
    --enum-field-as-literal all \
    --disable-timestamp \
    --use-double-quotes \
    --no-use-annotated \
    --allow-extra-fields \
    --custom-template-dir templates \
    --additional-imports pydantic.ConfigDict


echo "Formatting generated models..."
uv run ruff format
uv run ruff check --fix "$OUTPUT_DIR"


# Record the source ref that produced this generated tree, so downstream
# consumers can verify provenance after upstream main moves.
GEN_CMD="$0 $*"
if [ -z "$*" ]; then
    GEN_CMD="$0"
fi
cat > "src/ucp_sdk/_schema_ref.py" <<EOF
# Auto-generated by generate_models.sh. Do not edit by hand.
"""Provenance metadata for the generated schema models."""

UCP_SCHEMA_REF = "$UCP_SCHEMA_REF"
"""Commit SHA on Universal-Commerce-Protocol/ucp the models were generated from."""

GENERATE_COMMAND = "$GEN_CMD"
"""The generate_models.sh invocation that produced the current tree."""
EOF
echo "Wrote provenance to src/ucp_sdk/_schema_ref.py: $UCP_SCHEMA_REF"


echo "Done. Models generated in $OUTPUT_DIR"
