# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from ..capability import BusinessSchema, PlatformSchema
from .types import description as description_1
from .types import reverse_domain_name

IdentityLinking = TypeAliasType(
    "IdentityLinking", Annotated[Any, Field(..., title="Identity Linking")]
)
"""
Capability schema for identity linking. Businesses declare the user-authenticated scopes they offer in a flat 'scopes' map. Each key is the OAuth scope string as it appears on the wire ('{capability}:{scope}', e.g. 'dev.ucp.shopping.order:read'). Scope presence implies that the corresponding operations require user authentication. Operations not gated by any listed scope operate at whatever access level the business permits; UCP does not prescribe a default.
"""


class ScopePolicy(BaseModel):
    """
    Per-scope policy and metadata — auth constraints (e.g. min_acr, max_token_age), declarative metadata (e.g. claims produced, consent descriptions), or any other scope-specific configuration. An empty object means user authentication is required with no additional policy. Open for non-breaking extension.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    description: description_1.Description | None = None
    """
    Optional human-readable description of the scope that platforms can use to present and explain context (requirement and value) to the user.
    """


ScopeToken = TypeAliasType(
    "ScopeToken",
    Annotated[
        str,
        Field(
            ...,
            pattern="^[a-z](?:[a-z0-9-]*[a-z0-9])?(?:\\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9_])?)+:[a-z][a-z0-9_]*$",
        ),
    ],
)
"""
OAuth scope string formed by joining a capability name and a scope name with a colon: '{capability}:{scope}', e.g. 'dev.ucp.shopping.order:read'. Capability names use reverse-DNS naming; scope names denote the permission granted, defined by each capability's spec (e.g. 'read', 'manage', 'create'). Platforms request these strings verbatim in OAuth 'scope' parameters; issued tokens carry them in the 'scope' claim.
"""


class Provider(BaseModel):
    """
    A trusted identity provider for delegated authentication, keyed by the 'type' discriminator. 'oauth2' denotes an OAuth 2.0 / OIDC authorization server. Future versions MAY define additional types (e.g. wallet attestation) as non-breaking extensions; platforms MUST treat entries whose 'type' they do not support as filtered out (see Provider Selection).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    """
    Provider mechanism discriminator. 'oauth2' for OAuth 2.0 / OIDC authorization servers. Additional values MAY be defined by future versions; the value is an open string, not a closed enum, so unrecognized types remain valid and are filtered at runtime.
    """


class Config(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    providers: (
        dict[reverse_domain_name.ReverseDomainName, list[Provider]] | None
    ) = None
    """
    Map of trusted external identity providers keyed by reverse-domain identifier. Each key maps to an array of mechanism entries — an IdP namespace MAY offer multiple token acquisition mechanisms. Declares which upstream IdPs the business will accept JWT bearer assertions from for the Accelerated IdP Flow (chaining via RFC 8693 + RFC 7523). This field is additive: direct OAuth against the business domain via RFC 8414 discovery is always available regardless of 'providers' content. Businesses MUST NOT list their own authorization server here — chaining-to-self is degenerate, and direct OAuth covers that path. When absent, empty, or when no listed mechanism is supported by the platform, platforms run direct OAuth on the business domain.
    """
    scopes: dict[ScopeToken, ScopePolicy]
    """
    Map of user-authenticated scopes offered by this business. Each key is an OAuth scope string formed as '{capability}:{scope}' (e.g. 'dev.ucp.shopping.order:read'). Scope presence in this map declares that the corresponding operations require a user identity token. Operations not gated by any listed scope operate at whatever access level the business permits; UCP does not prescribe a default. Each value is a per-scope policy object (empty object means user auth required with no additional policy).
    """


class IdentityLinkingPlatformSchema(PlatformSchema):
    """
    Platform-level identity linking capability declaration. Platforms advertise support for identity linking; no auth-specific config is required.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class IdentityLinkingBusinessSchema(BusinessSchema):
    """
    Business-level identity linking configuration. Businesses declare the user-authenticated scopes they offer in 'config.scopes'.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    config: Config
