# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .. import ucp as ucp_1
from .types import context as context_1
from .types import (
    location,
    location_distance,
    location_filter,
    location_serves,
    message,
)
from .types import pagination as pagination_1
from .types import signals as signals_1


class LocationSearch(BaseModel):
    """
    Location search capability. Supports natural language queries, distance and serviceability relations, structured filtering including current item availability, and pagination.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class SearchRequest(BaseModel):
    """
    Request body for location search. The `distance` and `serves` relations and every supplied `filters` predicate combine with AND; `query` does not relax them.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    query: str | None = None
    """
    Free-text search query for natural language location search (e.g., 'restaurants near me that deliver', 'hotels with pool').
    """
    context: context_1.Context | None = None
    signals: signals_1.Signals | None = None
    distance: location_distance.LocationDistance | None = None
    """
    Optional explicit-center radius predicate. When present, it combines with `serves` and every supplied `filters` predicate using AND.
    """
    serves: location_serves.LocationServes | None = None
    """
    Optional authoritative service-target predicate. When present, it combines with `distance` and every supplied `filters` predicate using AND.
    """
    filters: location_filter.LocationFilter | None = None
    pagination: pagination_1.Request | None = None


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.ResponseLocationSchema
    locations: list[location.Location]
    """
    Locations matching the search criteria.
    """
    pagination: pagination_1.Response | None = None
    messages: list[message.Message] | None = None
    """
    Errors, warnings, or informational messages about the search results.
    """
