# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .. import ucp as ucp_1
from .types import context as context_1
from .types import location_distance, location_filter, location_serves, message
from .types import signals as signals_1
from .types.location import Location


class LocationLookup(BaseModel):
    """
    Location lookup by identifiers. Supports batch retrieval and single-location detail.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class Input(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    The identifier exactly as supplied in the lookup request.
    """


class LookupRequest(BaseModel):
    """
    Request body for batch location lookup. The Business resolves and deduplicates `ids` before applying `distance`, `serves`, and every supplied `filters` predicate; all structured predicates combine with AND.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ids: list[str] = Field(..., min_length=1)
    """
    Identifiers of the Locations to look up. The Business MUST support canonical `Location.id` values and MAY support secondary or alias identifiers.
    """
    distance: location_distance.LocationDistance | None = None
    """
    Optional explicit-center radius predicate applied after ID resolution. It combines with `serves` and every supplied `filters` predicate using AND.
    """
    serves: location_serves.LocationServes | None = None
    """
    Optional authoritative service-target predicate applied after ID resolution. It combines with `distance` and every supplied `filters` predicate using AND.
    """
    filters: location_filter.LocationFilter | None = None
    context: context_1.Context | None = None
    signals: signals_1.Signals | None = None


class LookupLocation(Location):
    """
    Location with required correlation metadata for lookup responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    inputs: list[Input] = Field(..., min_length=1)
    """
    Which request identifiers resolved to this Location. Each entry preserves one identifier exactly as supplied in the request.
    """


class LookupResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.ResponseLocationSchema
    locations: list[LookupLocation]
    """
    Locations matching the requested identifiers and refinements. May contain fewer Locations if some identifiers do not resolve or their resolved Locations are filtered out, or more if one identifier resolves to multiple Locations. When multiple identifiers resolve to the same Location, one returned Location carries all corresponding `inputs` entries.
    """
    messages: list[message.Message] | None = None
    """
    Errors, warnings, or informational messages about the requested Locations, including `batch_limit_applied` when the Business processes only its configured maximum number of identifiers.
    """
