# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from ..shopping.cart import Cart as Cart_1
from ..shopping.catalog_lookup import GetProductResponse, LookupResponse
from ..shopping.catalog_search import SearchResponse
from ..shopping.checkout import Checkout as Checkout_1
from .types import reverse_domain_name

LoyaltyExtension = TypeAliasType(
    "LoyaltyExtension", Annotated[Any, Field(..., title="Loyalty Extension")]
)
"""
Extends various Capabilities with loyalty support using memberships info.
"""


RewardAmount = TypeAliasType("RewardAmount", Annotated[int, Field(..., ge=0)])
"""
Non-negative integer amount denominated in the minor unit of the associated reward currency. The associated reward currency's `decimal_places` defines the minor-to-major ratio and defaults to 0 when omitted.
"""


class EarningBreakdown(BaseModel):
    """
    Breakdown rule of the reward earnings
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique rewards breakdown rule identifier.
    """
    amount: RewardAmount
    """
    Rewards earned from this rule.
    """
    description: str
    """
    A display-ready, human-readable rationale for the specific rewards (e.g. 2x on footwear).
    """
    benefit_id: str | None = None
    """
    Optional `id` of the membership_tier_benefit that produced this rewards rule. Resolves against `membership_tier_benefit.id` within the same parent loyalty membership.
    """


class EarningForecast(BaseModel):
    """
    Preview of rewards to be earned from the current transaction.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    amount: RewardAmount
    """
    Total rewards to be earned if the transaction completes.
    """
    breakdown: list[EarningBreakdown] | None = None
    """
    List of breakdown of earning contributing to the total.
    """


class RewardCurrency(BaseModel):
    """
    The currency of the loyalty reward.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    """
    Human-readable name of the currency (e.g. 'LoyaltyStars').
    """
    code: str
    """
    Business-specific representation of the currency (e.g. 'LST').
    """
    decimal_places: int | None = Field(0, ge=0)
    """
    The position of a digit to the right of a decimal point. Applies to all amount related fields for rewards.
    """


class Currency(BaseModel):
    """
    A unit of value that customers can accumulate through various commercial activities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    name: str
    """
    Human-readable name of the currency (e.g. 'LoyaltyStars').
    """
    code: str
    """
    Business-specific representation of the currency (e.g. 'LST').
    """
    decimal_places: int | None = Field(0, ge=0)
    """
    The position of a digit to the right of a decimal point. Applies to all amount related fields for rewards.
    """


class MembershipReward(BaseModel):
    """
    Quantifiable reward type and optional earning forecast for the current transaction.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    currency: Currency
    """
    A unit of value that customers can accumulate through various commercial activities.
    """
    earning_forecast: EarningForecast | None = None
    """
    Preview of rewards to be earned from the current transaction.
    """


class MembershipTierBenefit(BaseModel):
    """
    Benefits associated with a membership tier.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique identifier for the tier benefit.
    """
    description: str
    """
    A display-ready, human-readable explanation of this benefit (e.g. 'Early access to sales').
    """


class MembershipTier(BaseModel):
    """
    Specific achievement rank or status milestone that unlocks escalating value as a member progresses through activity or spend.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique identifier for the membership tier.
    """
    name: str
    """
    The human-readable name of the tier (e.g., 'Platinum').
    """
    benefits: list[MembershipTierBenefit] | None = None
    """
    List of benefits associated with this tier.
    """


class LoyaltyMembership(BaseModel):
    """
    Loyalty membership the business has accepted for the eligibility claim represented by the parent map key. Programs that can be joined independently MUST be modeled as separate sibling entries under the loyalty map, distinguished by reverse-domain naming (e.g., 'com.example.rewards' and 'com.example.rewards.card').
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique loyalty membership identifier.
    """
    name: str
    """
    Business specific name of the loyalty membership/program.
    """
    display_id: str | None = None
    """
    A masked or partial version of the membership id for user recognition (e.g., '****5678'). MUST NOT be set if the membership has not been verified.
    """
    tiers: list[MembershipTier] | None = None
    """
    Active or display-safe tier context for this membership. Most programs are single-status (one entry); programs with parallel status dimensions (e.g., current and lifetime) populate one entry per active tier. Omitted when no tier context has been resolved.
    """
    rewards: list[MembershipReward] | None = None
    """
    Reward types and earning forecasts associated with this membership. Each object encapsulates one type of reward.
    """
    provisional: bool
    """
    True if this membership requires additional verification.
    """


Loyalty = TypeAliasType(
    "Loyalty", dict[reverse_domain_name.ReverseDomainName, LoyaltyMembership]
)
"""
Key-value map whose keys represent buyer/platform asserted eligibility claims and whose values represent associated membership information. All loyalty keys MUST use reverse-domain naming to ensure provenance and prevent collisions when multiple extensions contribute to the shared namespace.
"""


class Search(SearchResponse):
    """
    Catalog Search response extended with Loyalty capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    loyalty: Loyalty | None = None


class Lookup1(LookupResponse):
    """
    Catalog Lookup response extended with Loyalty capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    loyalty: Loyalty | None = None


class Lookup2(GetProductResponse):
    """
    Catalog Lookup response extended with Loyalty capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    loyalty: Loyalty | None = None


Lookup = TypeAliasType(
    "Lookup",
    Annotated[
        Lookup1 | Lookup2, Field(..., title="Catalog Lookup with Loyalty")
    ],
)
"""
Catalog Lookup response extended with Loyalty capability.
"""


class Cart(Cart_1):
    """
    Cart extended with Loyalty capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    loyalty: Loyalty | None = None


class Checkout(Checkout_1):
    """
    Checkout extended with Loyalty capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    loyalty: Loyalty | None = None
