# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from ..shopping.checkout import Checkout as Checkout_1
from ..shopping.order import Order as Order_1
from .types import payment_term

PaymentTermsExtension = TypeAliasType(
    "PaymentTermsExtension",
    Annotated[Any, Field(..., title="Payment Terms Extension")],
)
"""
Extends capabilities (e.g., checkout in retail shopping) with selectable payment terms, letting a Business offer alternative schedules for when payment for the checkout is due, and projects the accepted term onto the resulting Order.
"""


PaymentTerm = TypeAliasType("PaymentTerm", payment_term.PaymentTerm)


class Payment(BaseModel):
    """
    Payment object extended with selectable payment terms.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    terms: list[PaymentTerm] | None = Field(None, min_length=1)
    """
    Payment terms the Buyer can choose from. An unselected term's amounts are indicative; the selected term's schedule amounts sum to the checkout total.
    """
    selected_term_id: str | None = None
    """
    ID of the selected payment term. MUST match one `terms[].id` from the latest Checkout response. Present in a response whenever `terms` is, and absent when it is not: the Checkout total is the selected term's total, so a list of terms without a selection would show an amount that matches no stated term. Where the Buyer has made no choice, the Business selects a default. Omitted on create requests because term IDs are checkout-scoped and no terms exist yet, and on complete requests because the term is already agreed by then. Selecting a term is an Update Checkout mutation: the Business response is authoritative for all derived state.
    """


class OrderPayment(BaseModel):
    """
    Order payment details carrying the term the Buyer accepted at checkout.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    accepted_term: PaymentTerm | None = None
    """
    The payment term the Buyer accepted at checkout. Businesses MUST carry it forward so the Order states the amounts owed and when, and MUST ensure its schedule amounts sum to the Order total. The available terms are checkout state and are not projected.
    """


class Checkout(Checkout_1):
    """
    Checkout extended with selectable payment terms.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    payment: Payment | None = None
    """
    Payment details with available and selected payment terms.
    """


class Order(Order_1):
    """
    Order extended with the payment term accepted at checkout.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    payment: OrderPayment | None = None
    """
    Payment details for the Order, including the accepted payment term.
    """
