# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from ..shopping.checkout import Checkout as Checkout_1

PaymentAuthenticationExtension = TypeAliasType(
    "PaymentAuthenticationExtension",
    Annotated[Any, Field(..., title="Payment Authentication Extension")],
)
"""
Extends capabilities (e.g., checkout in retail shopping) with standard device data collection and 3DS challenge Action types used during payment authentication.
"""


class Config(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    payment_instrument_id: str = Field(..., min_length=1)
    """
    ID of the payment instrument in the containing Checkout associated with this device data collection Action.
    """
    url: AnyUrl
    """
    URL for the invisible device data collection surface.
    """


class DevUcpCommonPaymentDeviceDataCollectionItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    config: Config


class Config2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    payment_instrument_id: str = Field(..., min_length=1)
    """
    ID of the payment instrument in the containing Checkout associated with this 3DS challenge Action.
    """
    url: AnyUrl
    """
    URL for the buyer-facing 3DS challenge surface.
    """


class DevUcpCommonPaymentThreeDsChallengeItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    config: Config2


class Actions(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    dev_ucp_common_payment_device_data_collection: (
        list[DevUcpCommonPaymentDeviceDataCollectionItem] | None
    ) = Field(None, alias="dev.ucp.common.payment.device_data_collection")
    """
    A 3DS device data collection Action.
    """
    dev_ucp_common_payment_three_ds_challenge: (
        list[DevUcpCommonPaymentThreeDsChallengeItem] | None
    ) = Field(None, alias="dev.ucp.common.payment.three_ds_challenge")
    """
    A 3DS challenge Action.
    """


class Checkout(Checkout_1):
    model_config = ConfigDict(
        extra="allow",
    )
    actions: Actions | None = None
