# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict

from .types import line_item, link, message, total


class Context(BaseModel):
    """
    Buyer signals for localization (country, region, postal_code). Merchant uses for pricing, availability, currency. Falls back to geo-IP if omitted.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address_country: str | None = None
    """
    The country. Recommended to be in 2-letter ISO 3166-1 alpha-2 format, for example "US". For backward compatibility, a 3-letter ISO 3166-1 alpha-3 country code such as "SGP" or a full country name such as "Singapore" can also be used. Optional hint for market context (currency, availability, pricing)—higher-resolution data (e.g., shipping address) supersedes this value.
    """
    address_region: str | None = None
    """
    The region in which the locality is, and which is in the country. For example, California or another appropriate first-level Administrative division. Optional hint for progressive localization—higher-resolution data (e.g., shipping address) supersedes this value.
    """
    postal_code: str | None = None
    """
    The postal code. For example, 94043. Optional hint for regional refinement—higher-resolution data (e.g., shipping address) supersedes this value.
    """
    intent: str | None = None
    """
    Background context describing buyer's intent (e.g., 'looking for a gift under $50', 'need something durable for outdoor use'). Informs relevance, recommendations, and personalization.
    """


class Buyer(BaseModel):
    """
    Optional buyer information for personalized estimates.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    first_name: str | None = None
    """
    First name of the buyer.
    """
    last_name: str | None = None
    """
    Last name of the buyer.
    """
    email: str | None = None
    """
    Email of the buyer.
    """
    phone_number: str | None = None
    """
    E.164 standard.
    """


class Cart(BaseModel):
    """
    Shopping cart with estimated pricing before checkout. Lightweight pre-purchase exploration with no payment info or complex status states. Cart exists (200) or doesn't (404).
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: Any
    id: str
    """
    Unique cart identifier.
    """
    line_items: list[line_item.LineItem]
    """
    Cart line items. Same structure as checkout. Full replacement on update.
    """
    context: Context | None = None
    """
    Buyer signals for localization (country, region, postal_code). Merchant uses for pricing, availability, currency. Falls back to geo-IP if omitted.
    """
    buyer: Buyer | None = None
    """
    Optional buyer information for personalized estimates.
    """
    currency: str
    """
    ISO 4217 currency code. Determined by merchant based on context or geo-IP.
    """
    totals: list[total.Total]
    """
    Estimated cost breakdown. May be partial if shipping/tax not yet calculable.
    """
    messages: list[message.Message] | None = None
    """
    Validation messages, warnings, or informational notices.
    """
    links: list[link.Link] | None = None
    """
    Optional merchant links (policies, FAQs).
    """
    continue_url: AnyUrl | None = None
    """
    URL for cart handoff and session recovery. Enables sharing and human-in-the-loop flows.
    """
    expires_at: AwareDatetime | None = None
    """
    Cart expiry timestamp (RFC 3339). Optional.
    """
