# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field

from .types import line_item, link, message, payment_instrument, total


class Ucp(BaseModel):
    """
    UCP metadata for checkout responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: str = Field(..., pattern="^\\d{4}-\\d{2}-\\d{2}$")
    """
    UCP version in YYYY-MM-DD format.
    """
    services: Any | None = None
    capabilities: Any | None = None
    payment_handlers: Any


class Buyer(BaseModel):
    """
    Representation of the buyer.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    first_name: str | None = None
    """
    First name of the buyer.
    """
    last_name: str | None = None
    """
    Last name of the buyer.
    """
    email: str | None = None
    """
    Email of the buyer.
    """
    phone_number: str | None = None
    """
    E.164 standard.
    """


class Context(BaseModel):
    """
    Provisional buyer signals for relevance and localization: product availability, pricing, currency, tax, shipping, payment methods, and eligibility (e.g., student or affiliation discounts). Businesses SHOULD use these values when authoritative data (e.g., address) is absent, and MAY ignore unsupported values without returning errors. Context SHOULD be non-identifying and can be disclosed progressively—coarse signals early, finer resolution as the session progresses. Higher-resolution data (shipping address, billing address) supersedes context. Platforms SHOULD progressively enhance context throughout the buyer journey.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address_country: str | None = None
    """
    The country. Recommended to be in 2-letter ISO 3166-1 alpha-2 format, for example "US". For backward compatibility, a 3-letter ISO 3166-1 alpha-3 country code such as "SGP" or a full country name such as "Singapore" can also be used. Optional hint for market context (currency, availability, pricing)—higher-resolution data (e.g., shipping address) supersedes this value.
    """
    address_region: str | None = None
    """
    The region in which the locality is, and which is in the country. For example, California or another appropriate first-level Administrative division. Optional hint for progressive localization—higher-resolution data (e.g., shipping address) supersedes this value.
    """
    postal_code: str | None = None
    """
    The postal code. For example, 94043. Optional hint for regional refinement—higher-resolution data (e.g., shipping address) supersedes this value.
    """
    intent: str | None = None
    """
    Background context describing buyer's intent (e.g., 'looking for a gift under $50', 'need something durable for outdoor use'). Informs relevance, recommendations, and personalization.
    """


class Order(BaseModel):
    """
    Details about an order created for this checkout session.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique order identifier.
    """
    permalink_url: AnyUrl
    """
    Permalink to access the order on merchant site.
    """


class Payment(BaseModel):
    """
    Payment configuration containing handlers.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    instruments: list[payment_instrument.SelectedPaymentInstrument] | None = None
    """
    The payment instruments available for this payment. Each instrument is associated with a specific handler via the handler_id field. Handlers can extend the base payment_instrument schema to add handler-specific fields.
    """


class Checkout(BaseModel):
    """
    Base checkout schema. Extensions compose onto this using allOf.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp: Ucp
    id: str
    """
    Unique identifier of the checkout session.
    """
    line_items: list[line_item.LineItem]
    """
    List of line items being checked out.
    """
    buyer: Buyer | None = None
    """
    Representation of the buyer.
    """
    context: Context | None = None
    status: Literal[
        "incomplete",
        "requires_escalation",
        "ready_for_complete",
        "complete_in_progress",
        "completed",
        "canceled",
    ]
    """
    Checkout state indicating the current phase and required action. See Checkout Status lifecycle documentation for state transition details.
    """
    currency: str
    """
    ISO 4217 currency code reflecting the merchant's market determination. Derived from address, context, and geo IP—buyers provide signals, merchants determine currency.
    """
    totals: list[total.Total]
    """
    Different cart totals.
    """
    messages: list[message.Message] | None = None
    """
    List of messages with error and info about the checkout session state.
    """
    links: list[link.Link]
    """
    Links to be displayed by the platform (Privacy Policy, TOS). Mandatory for legal compliance.
    """
    expires_at: AwareDatetime | None = None
    """
    RFC 3339 expiry timestamp. Default TTL is 6 hours from creation if not sent.
    """
    continue_url: AnyUrl | None = None
    """
    URL for checkout handoff and session recovery. MUST be provided when status is requires_escalation. See specification for format and availability requirements.
    """
    payment: Payment | None = None
    order: Order | None = None
    """
    Details about an order created for this checkout session.
    """
