# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import ConfigDict, Field
from typing_extensions import TypeAliasType

from .checkout_update_request import CheckoutUpdateRequest
from .types import (
    fulfillment_available_method_update_request,
    fulfillment_group_update_request,
    fulfillment_method_update_request,
    fulfillment_option_update_request,
    fulfillment_update_request,
)

FulfillmentExtensionUpdateRequest = TypeAliasType(
    "FulfillmentExtensionUpdateRequest",
    Annotated[Any, Field(..., title="Fulfillment Extension Update Request")],
)
"""
Extends Checkout with fulfillment support using methods, destinations, and groups.
"""


FulfillmentOption = TypeAliasType(
    "FulfillmentOption",
    fulfillment_option_update_request.FulfillmentOptionUpdateRequest,
)


FulfillmentGroup = TypeAliasType(
    "FulfillmentGroup",
    fulfillment_group_update_request.FulfillmentGroupUpdateRequest,
)


FulfillmentAvailableMethod = TypeAliasType(
    "FulfillmentAvailableMethod",
    fulfillment_available_method_update_request.FulfillmentAvailableMethodUpdateRequest,
)


DevUcpShoppingFulfillment = TypeAliasType("DevUcpShoppingFulfillment", Any)


FulfillmentMethod = TypeAliasType(
    "FulfillmentMethod",
    fulfillment_method_update_request.FulfillmentMethodUpdateRequest,
)


Fulfillment = TypeAliasType(
    "Fulfillment", fulfillment_update_request.FulfillmentUpdateRequest
)


class Checkout(CheckoutUpdateRequest):
    """
    Checkout extended with hierarchical fulfillment.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    fulfillment: Fulfillment | None = None
    """
    Fulfillment details.
    """
