# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

PermalinkCapability = TypeAliasType(
    "PermalinkCapability",
    Annotated[Any, Field(..., title="Permalink Capability")],
)
"""
Browser-addressable shopping intent capability: defines a Business browser endpoint and redirect resolution. It defines no shopping-state fields of its own; permalink query parameters address existing UCP field paths.
"""


Endpoint = TypeAliasType("Endpoint", AnyUrl)
"""
Absolute HTTPS browser endpoint with a non-empty authority and without userinfo, query, fragment, whitespace, backslashes, or trailing slash. Optional compact item path and query parameters are appended to this endpoint.
"""


class Config(BaseModel):
    """
    Business browser endpoint configuration for shopping permalinks.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    endpoint: Endpoint


Permalink = TypeAliasType("Permalink", Any)
