# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from ..common.types import amount as amount_1
from .checkout import Checkout as Checkout_1
from .types import instrument_group
from .types.payment_instrument import PaymentInstrument as PaymentInstrument_1

SplitPaymentsExtension = TypeAliasType(
    "SplitPaymentsExtension",
    Annotated[Any, Field(..., title="Split Payments Extension")],
)
"""
Enables buyers to use multiple payment instruments for a single checkout.
"""


InstrumentGroup = TypeAliasType(
    "InstrumentGroup", instrument_group.InstrumentGroup
)


SplitPayments = TypeAliasType("SplitPayments", Any)


class PaymentInstrument(PaymentInstrument_1):
    """
    Payment instrument extended with an optional per-instrument amount for split payments.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    amount: amount_1.Amount | None = None
    """
    Contribution amount for this instrument in `checkout.currency` minor units (ISO 4217). On request: the platform's requested contribution (omit for open-amount). On response: the actual amount authorized or charged (omitted when not finally processed).
    """


class Payment(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    instruments: list[PaymentInstrument] | None = None
    """
    Payment instruments in allocation priority order.
    """


class Checkout(Checkout_1):
    """
    Checkout extended with split payment instrument amounts.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    payment: Payment | None = None
