# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class MultiDestinationItem(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    method: str
    """
    Fulfillment method type (e.g. `shipping`, `pickup`). Optional per-method constraints MAY be added alongside.
    """


class BusinessFulfillmentConfig(BaseModel):
    """
    Business's fulfillment configuration.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    multi_destination: list[MultiDestinationItem] | None = None
    """
    Method types that permit multiple destinations within one cart (e.g. split shipping across addresses). Listing a method permits it; an omitted method does not. Open — businesses MAY list any method type.
    """
    method_combinations: list[list[str]] | None = None
    """
    Method-type combinations the business permits within one cart. Each inner array is a permitted set of method `type` values (e.g. shipping + pickup).
    """
