# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import fulfillment_destination, fulfillment_group


class FulfillmentMethod(BaseModel):
    """
    A fulfillment method with destinations and groups.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique fulfillment method identifier.
    """
    type: str
    """
    Fulfillment method type. Well-known values: `shipping`, `pickup`. Businesses MAY use additional values.
    """
    line_item_ids: list[str]
    """
    Line item IDs fulfilled via this method.
    """
    destinations: (
        list[fulfillment_destination.FulfillmentDestination] | None
    ) = None
    """
    Available destinations for this method. In Business responses, each destination carries a `type` and `id`.
    """
    selected_destination_id: str | None = None
    """
    ID of the selected destination. Accepts any stable, Business-scoped ID the Business recognizes for this method, including Location IDs not yet enumerated in `destinations`.
    """
    groups: list[fulfillment_group.FulfillmentGroup] | None = None
    """
    Fulfillment groups for selecting options. Agent sets selected_option_id on groups to choose shipping method.
    """
