# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import ConfigDict, Field, RootModel

from . import (
    retail_location_create_request,
    shipping_destination_create_request,
)


class FulfillmentDestinationCreateRequest(
    RootModel[
        shipping_destination_create_request.ShippingDestinationCreateRequest
        | retail_location_create_request.RetailLocationCreateRequest
    ]
):
    model_config = ConfigDict(
        frozen=True,
    )
    root: (
        shipping_destination_create_request.ShippingDestinationCreateRequest
        | retail_location_create_request.RetailLocationCreateRequest
    ) = Field(..., title="Fulfillment Destination Create Request")
    """
    A destination for fulfillment.
    """
