# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict, Field

from .payment_credential import PaymentCredential


class NetworkTokenCredential(PaymentCredential):
    """
    A card-network token credential verified with a transaction cryptogram. The `number` field carries the network token or wallet-provisioned token rather than the underlying FPAN.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["network_token"]
    """
    The credential type identifier for network token credentials.
    """
    number: str = Field(..., examples=["5204240000004242"])
    """
    Network token or wallet-provisioned token replacing the underlying FPAN.
    """
    expiry_month: int | None = None
    """
    The month of the token's expiration date (1-12).
    """
    expiry_year: int | None = None
    """
    The year of the token's expiration date.
    """
    name: str | None = Field(None, examples=["Jane Doe"])
    """
    Cardholder name.
    """
    cryptogram: str = Field(..., examples=["gXc5UCLnM6ckD7pjM1TdPA=="])
    """
    Transaction cryptogram or dynamic CVC (dCVV), in the long or short form expected by the card network or processor.
    """
    eci_value: str | None = Field(None, examples=["07"])
    """
    Electronic Commerce Indicator / Security Level Indicator associated with the transaction.
    """
    token_requestor_id: str | None = Field(None, examples=["12345678901"])
    """
    Payment network token requestor identifier, when required by the processor or network-token program.
    """
