# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from ...common.types import total_update_request
from . import item_update_request


class Quantity(BaseModel):
    """
    Tracks the line item's original, current active, and fulfilled quantities. All three values use the same inherited `item.quantity_unit`. When `item.quantity_unit` is absent on an authoritative order response, each step is one whole item (`each`) under the shared default.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    original: int | None = Field(None, ge=0, le=9007199254740991)
    """
    Quantity from the original checkout, expressed as an integer step count.
    """
    total: int = Field(..., ge=0, le=9007199254740991)
    """
    Current active quantity after returns, cancellations, or other order changes, expressed as an integer step count.
    """
    fulfilled: int = Field(..., ge=0, le=9007199254740991)
    """
    Quantity fulfilled so far, expressed as an integer step count.
    """


class OrderLineItemUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Line item identifier.
    """
    item: item_update_request.ItemUpdateRequest
    """
    Purchased item data, including identity, price, and sale basis.
    """
    quantity: Quantity
    """
    Tracks the line item's original, current active, and fulfilled quantities. All three values use the same inherited `item.quantity_unit`. When `item.quantity_unit` is absent on an authoritative order response, each step is one whole item (`each`) under the shared default.
    """
    totals: list[total_update_request.TotalUpdateRequest]
    """
    Line item totals breakdown.
    """
    status: Literal["processing", "partial", "fulfilled", "removed"]
    """
    Derived status: removed if quantity.total == 0, fulfilled if quantity.total > 0 and quantity.fulfilled == quantity.total, partial if quantity.total > 0 and quantity.fulfilled > 0, otherwise processing.
    """
    parent_id: str | None = None
    """
    Parent line item identifier for any nested structures.
    """
