# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Literal

from pydantic import ConfigDict, Field

from .payment_credential import PaymentCredential


class PanCredential(PaymentCredential):
    """
    A card credential carrying a funding primary account number (FPAN). Credential selection follows the shape of the value on the wire rather than its provenance: a network token surfaced in PAN form and verified with a `cvc` — as with credentials where a dynamic verification code proxies the cryptogram — is carried here, while a token verified with a discrete `cryptogram` uses Network Token Credential. This credential type MUST NOT be used for checkout, only with payment handlers that tokenize or encrypt credentials. CRITICAL: Both parties handling a PAN credential (sender and receiver) MUST be PCI DSS compliant. Transmission MUST use HTTPS/TLS with strong cipher suites.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["pan"]
    """
    The credential type identifier for PAN credentials.
    """
    number: str = Field(..., examples=["4242424242424242"])
    """
    Funding primary account number (FPAN).
    """
    expiry_month: int | None = None
    """
    The month of the card's expiration date (1-12).
    """
    expiry_year: int | None = None
    """
    The year of the card's expiration date.
    """
    name: str | None = Field(None, examples=["Jane Doe"])
    """
    Cardholder name.
    """
    cvc: str | None = Field(None, examples=["223"], max_length=4)
    """
    Card verification code.
    """
