# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated

from pydantic import Field, AfterValidator
from typing_extensions import TypeAliasType

from . import total_update_request


def _enforce_contains_totals_update_request(value):
    """JSON Schema contains/minContains/maxContains (see #49)."""
    _matched_0 = sum(
        1
        for _item in value
        if (
            _item.get("type")
            if isinstance(_item, dict)
            else getattr(_item, "type", None)
        )
        == "subtotal"
    )
    if _matched_0 < 1:
        raise ValueError(
            "Array must contain at least 1 entry "
            "matching type=='subtotal' (schema minContains=1)"
        )
    if _matched_0 > 1:
        raise ValueError(
            "Array must contain at most 1 entry "
            "matching type=='subtotal' (schema maxContains=1)"
        )
    _matched_1 = sum(
        1
        for _item in value
        if (
            _item.get("type")
            if isinstance(_item, dict)
            else getattr(_item, "type", None)
        )
        == "total"
    )
    if _matched_1 < 1:
        raise ValueError(
            "Array must contain at least 1 entry "
            "matching type=='total' (schema minContains=1)"
        )
    if _matched_1 > 1:
        raise ValueError(
            "Array must contain at most 1 entry "
            "matching type=='total' (schema maxContains=1)"
        )
    _excluded = [
        "subtotal",
        "items_discount",
        "discount",
        "fulfillment",
        "tax",
        "fee",
        "total",
    ]
    for _item in value:
        _actual = (
            _item.get("type")
            if isinstance(_item, dict)
            else getattr(_item, "type", None)
        )
        if _actual in _excluded:
            continue
        if isinstance(_item, dict) and "display_text" not in _item:
            raise ValueError("Field 'display_text' is required for custom type")
        if (
            not isinstance(_item, dict)
            and "display_text" not in _item.model_fields_set
        ):
            raise ValueError("Field 'display_text' is required for custom type")
    return value


TotalsUpdateRequest = TypeAliasType(
    "TotalsUpdateRequest",
    Annotated[
        list[total_update_request.TotalUpdateRequest],
        Field(..., title="Totals Update Request"),
        AfterValidator(_enforce_contains_totals_update_request),
    ],
)
"""
Pricing breakdown provided by the business. MUST contain exactly one subtotal and one total entry. Detail types (tax, fee, discount, fulfillment) may appear multiple times for itemization. Platforms MUST render all entries in order using display_text and amount.
"""
