# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from ...common.types import amount as amount_1
from ...common.types.measure import Measure as Measure_1


class Measure(Measure_1):
    """
    Product quantity in packaging/content (for example, a 750 mL bottle), distinct from `quantity_unit`, which defines the sale basis. Its integer `value` MUST be at least 1.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    value: Any | None = Field(None, ge=1)


class Reference(Measure_1):
    """
    Denominator for unit price display (for example, per 100 mL or per 1 kg). Its integer `value` MUST be at least 1.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    value: Any | None = Field(None, ge=1)


class UnitPrice(BaseModel):
    """
    Price per standard unit of measurement. MAY be omitted when unit pricing does not apply. `unit_price.currency` MUST equal `price.currency`; the comparator MUST NOT perform currency conversion. `measure.unit` and `reference.unit` MUST be identical; cross-unit conversion is not permitted. Their scales MAY differ; each value represents `value × 10^-scale`.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    amount: amount_1.Amount
    """
    Unit price in ISO 4217 minor units. After satisfying the same-unit invariant, the Business MUST compute the comparator as `(price.amount / (measure.value × 10^-measure.scale)) × (reference.value × 10^-reference.scale)` and round it once to ISO 4217 minor units according to its pricing rules. The returned `unit_price.amount` is authoritative; the Platform MUST NOT recompute or substitute its own result.
    """
    currency: str = Field(..., pattern="^[A-Z]{3}$")
    """
    ISO 4217 currency code.
    """
    measure: Measure
    """
    Product quantity in packaging/content (for example, a 750 mL bottle), distinct from `quantity_unit`, which defines the sale basis. Its integer `value` MUST be at least 1.
    """
    reference: Reference
    """
    Denominator for unit price display (for example, per 100 mL or per 1 kg). Its integer `value` MUST be at least 1.
    """
