# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import AnyUrl, BaseModel, ConfigDict

from ...common.types import description as description_1
from ...common.types import link
from ...common.types import media as media_1
from ...common.types import price as price_1
from ...common.types import quantity_unit as quantity_unit_1
from . import availability as availability_1
from . import category
from . import rating as rating_1
from . import selected_option
from . import unit_price as unit_price_1


class Barcode(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    """
    Barcode standard. Well-known values: UPC, EAN, ISBN, GTIN, JAN.
    """
    value: str
    """
    Barcode value.
    """


class Seller(BaseModel):
    """
    Optional seller context for this variant.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    """
    Seller display name.
    """
    links: list[link.Link] | None = None
    """
    Seller policy and information links.
    """


class Variant(BaseModel):
    """
    A purchasable variant of a product with specific option selections.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Global ID (GID) uniquely identifying this variant. Used as item.id in checkout.
    """
    sku: str | None = None
    """
    Business-assigned identifier for inventory and fulfillment.
    """
    barcodes: list[Barcode] | None = None
    """
    Industry-standard product identifiers for cross-reference and correlation.
    """
    handle: str | None = None
    """
    URL-safe variant handle/slug.
    """
    title: str
    """
    Variant display title (e.g., 'Blue / Large').
    """
    description: description_1.Description
    """
    Variant description in one or more formats.
    """
    url: AnyUrl | None = None
    """
    Canonical variant page URL.
    """
    categories: list[category.Category] | None = None
    """
    Variant categories with optional taxonomy identifiers.
    """
    price: price_1.Price
    """
    Current selling price. Price is the amount per one whole `quantity_unit.unit` (for example, per lb or per hour); when `quantity_unit` is absent, it is per `each`. Line total is `price × quantity × 10^-scale`, computed and rounded once by the Business; `totals` remain authoritative.
    """
    quantity_unit: quantity_unit_1.QuantityUnit | None = None
    """
    Sale basis this variant's `quantity` is denominated in. The default sale basis is `each`, whose machine identity is (`C62`, 0); `C62` is the UN/CEFACT Rec20 code for one/each. An absent catalog descriptor encodes that default. An `increment` advertises the ordering granularity in steps (for example, `scale` 2 with `increment` 25 sells in 0.25-unit multiples).
    """
    list_price: price_1.Price | None = None
    """
    List price before discounts (for strikethrough display).
    """
    unit_price: unit_price_1.UnitPrice | None = None
    """
    Price per standard unit of measurement, for shelf-style comparison display. MAY be omitted when unit pricing does not apply.
    """
    availability: availability_1.Availability | None = None
    """
    Variant availability for purchase.
    """
    options: list[selected_option.SelectedOption] | None = None
    """
    Option values that define this variant (e.g., Color: Blue, Size: Large).
    """
    media: list[media_1.Media] | None = None
    """
    Variant media (images, videos, 3D models). First item is the featured media for listings.
    """
    rating: rating_1.Rating | None = None
    """
    Variant rating.
    """
    tags: list[str] | None = None
    """
    Variant tags for categorization and search.
    """
    metadata: dict[str, Any] | None = None
    """
    Business-defined custom data extending the standard variant model.
    """
    seller: Seller | None = None
    """
    Optional seller context for this variant.
    """
