# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from .jsonrpc import Request, SuccessResponse


class Extension(BaseModel):
    """
    A2A Agent Card extension advertisement for UCP.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    uri: AnyUrl
    """
    Extension URI. UCP uses its versioned reference URI.
    """
    description: str | None = None
    params: dict[str, Any] | None = None
    """
    Extension parameters such as advertised UCP capabilities.
    """


class AgentCard(BaseModel):
    """
    A2A Agent Card fragment advertising UCP support through extensions.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    extensions: list[Extension] = Field(..., min_length=1)


class Part(BaseModel):
    """
    A2A message part. UCP examples use text parts for natural language and data parts for structured UCP payloads.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str | None = None
    kind: str | None = None
    text: str | None = None
    data: dict[str, Any] | None = None
    """
    Structured data payload. UCP reserves a2a.ucp.* keys for UCP payloads.
    """


class Message(BaseModel):
    """
    A2A Message carrying natural-language or structured UCP data parts.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    role: Literal["user", "agent"]
    """
    Message sender role.
    """
    parts: list[Part] = Field(..., min_length=1)
    messageId: str
    kind: Literal["message"]
    contextId: str


class Params(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    message: Message


class MessageRequest(Request):
    """
    A2A message/send JSON-RPC request whose params carry a UCP-bearing Message from the platform to the business agent.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    method: Literal["message/send"] | None = None
    params: Params


class MessageResponse(SuccessResponse):
    """
    JSON-RPC success response whose result is an A2A Message from the business agent.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    result: Message | None = None


A2AUcpMessageEnvelope = TypeAliasType(
    "A2AUcpMessageEnvelope",
    Annotated[
        AgentCard | MessageRequest | MessageResponse,
        Field(..., title="A2A UCP Message Envelope"),
    ],
)
"""
Minimal A2A envelope shapes used by UCP's A2A checkout binding. This schema validates UCP's transport mapping points — Agent Card extension advertisement, inbound A2A Message requests, and JSON-RPC responses carrying A2A Message results — without attempting to re-specify the full A2A protocol.
"""
