# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import ConfigDict, Field, model_validator
from typing_extensions import TypeAliasType

from . import jsonrpc
from .jsonrpc import Request as Request_1
from .jsonrpc import SuccessResponse

Method = TypeAliasType(
    "Method",
    Annotated[
        str,
        Field(
            ...,
            pattern="^(ec|ep\\.cart)\\.[a-z][a-z0-9_]*(?:\\.[a-z][a-z0-9_]*)*$",
        ),
    ],
)
"""
Embedded Protocol method name. Checkout methods use ec.* and cart methods use ep.cart.*.
"""


class Request(Request_1):
    """
    Embedded Protocol request or notification envelope. Messages with id expect a response; messages without id are notifications.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    method: Method | None = None
    params: dict[str, Any]
    """
    Capability-specific EP parameters.
    """


class Response(SuccessResponse):
    """
    Embedded Protocol success response envelope. UCP application-level success and error outcomes are both carried in result.ucp.status.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    result: dict[str, Any] | None = None
    """
    Capability-specific EP result. Application-level status is defined by capability schemas; see Embedded Protocol response handling.
    """

    @model_validator(mode="after")
    def _enforce_conditional_required(self):
        """JSON Schema if/then: enforce conditionally required fields."""
        rules = [
            {
                "discriminator": "has_next_page",
                "values": [True],
                "required": ["cursor"],
            }
        ]
        for rule in rules:
            if getattr(self, rule["discriminator"], None) not in rule["values"]:
                continue
            for field in rule["required"]:
                if field not in self.model_fields_set:
                    raise ValueError(
                        f"Field {field!r} is required by a schema condition"
                    )
        return self


ErrorResponse = TypeAliasType("ErrorResponse", jsonrpc.ErrorResponse)
"""
JSON-RPC transport-level error response for EP messages. Application-level failures use the response result with result.ucp.status=error instead.
"""


EmbeddedProtocolMessageEnvelope = TypeAliasType(
    "EmbeddedProtocolMessageEnvelope",
    Annotated[
        Request | Response | ErrorResponse,
        Field(..., title="Embedded Protocol Message Envelope"),
    ],
)
"""
JSON-RPC envelope for UCP Embedded Protocol (EP) messages exchanged between a host and an embedded context. This schema constrains the shared transport envelope and method namespace while leaving capability-specific params and result payloads to their capability schemas.
"""
