# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

Id = TypeAliasType("Id", str | float | None)
"""
JSON-RPC request identifier. Notifications omit id; responses echo the request id, or use null when the request id could not be determined.
"""


class Error(BaseModel):
    """
    JSON-RPC transport-level error object. UCP business outcomes use result payloads with UCP messages instead of this object.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    code: int
    """
    JSON-RPC error code. Standard codes are negative integers; UCP bindings reserve business errors for UCP messages.
    """
    message: str
    """
    Short transport-level error description.
    """
    data: Any | None = None
    """
    Optional machine-readable transport error details.
    """


class Request(BaseModel):
    """
    JSON-RPC request or notification envelope. Presence of id makes the message a request; absence of id makes it a notification.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    jsonrpc: Literal["2.0"]
    """
    JSON-RPC protocol version.
    """
    id: Id | None = None
    method: str = Field(..., min_length=1)
    """
    Transport method name. Binding-specific schemas constrain the method namespace.
    """
    params: dict[str, Any] | list[Any] | None = None
    """
    Method parameters. Binding-specific schemas define the object shape.
    """


class SuccessResponse(BaseModel):
    """
    JSON-RPC success response envelope.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    jsonrpc: Literal["2.0"]
    """
    JSON-RPC protocol version.
    """
    id: Id
    result: Any
    """
    Successful transport result. UCP bindings define the nested result payload.
    """


class ErrorResponse(BaseModel):
    """
    JSON-RPC transport error response envelope. This is for protocol-level failures, not UCP application-level messages.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    jsonrpc: Literal["2.0"]
    """
    JSON-RPC protocol version.
    """
    id: Id
    error: Error


JsonRpc20Envelope = TypeAliasType(
    "JsonRpc20Envelope",
    Annotated[
        Request | SuccessResponse | ErrorResponse,
        Field(..., title="JSON-RPC 2.0 Envelope"),
    ],
)
"""
Common JSON-RPC 2.0 transport envelope used by UCP JSON-RPC-based bindings. This schema intentionally validates only the protocol envelope; binding-specific params and result payloads are validated by transport-specific schemas or extracted UCP payload schemas.
"""
