# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator
from typing_extensions import TypeAliasType

from . import jsonrpc
from .jsonrpc import Request as Request_1
from .jsonrpc import SuccessResponse


class UcpAgent(BaseModel):
    """
    UCP-Agent metadata carried inside MCP tool arguments.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    profile: str
    """
    Platform profile URI advertised to the business.
    """


class Meta(BaseModel):
    """
    UCP request metadata passed through MCP params.arguments.meta.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ucp_agent: UcpAgent | None = Field(None, alias="ucp-agent")
    idempotency_key: str | None = Field(None, alias="idempotency-key")
    """
    Optional idempotency key for retry-safe mutating operations.
    """


class Arguments(BaseModel):
    """
    MCP tool arguments. UCP reserves meta for transport metadata; operation payload fields such as checkout, cart, order id, or catalog inputs are operation-specific.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    meta: Meta | None = None


class Params(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., min_length=1)
    """
    MCP tool name matching the UCP operation binding, such as create_checkout or get_cart.
    """
    arguments: Arguments


class Request(Request_1):
    """
    MCP tools/call request envelope for invoking a UCP operation.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    method: Literal["tools/call"] | None = None
    params: Params


class ContentPart(BaseModel):
    """
    MCP content part returned for clients that do not consume structuredContent.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    text: str | None = None


class Result(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    structuredContent: dict[str, Any]
    """
    The UCP response payload for the operation.
    """
    content: list[ContentPart] | None = None


class Response(SuccessResponse):
    """
    MCP tools/call response envelope. UCP payloads are carried in result.structuredContent; content is compatibility output.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    result: Result | None = None

    @model_validator(mode="after")
    def _enforce_conditional_required(self):
        """JSON Schema if/then: enforce conditionally required fields."""
        rules = [
            {
                "discriminator": "has_next_page",
                "values": [True],
                "required": ["cursor"],
            }
        ]
        for rule in rules:
            if getattr(self, rule["discriminator"], None) not in rule["values"]:
                continue
            for field in rule["required"]:
                if field not in self.model_fields_set:
                    raise ValueError(
                        f"Field {field!r} is required by a schema condition"
                    )
        return self


McpToolCallEnvelope = TypeAliasType(
    "McpToolCallEnvelope",
    Annotated[
        Request | Response | jsonrpc.ErrorResponse,
        Field(..., title="MCP Tool Call Envelope"),
    ],
)
"""
UCP's MCP transport envelope for JSON-RPC tools/call messages. The schema validates the MCP mapping layer: operation name in params.name, UCP metadata and domain arguments in params.arguments, and UCP output in result.structuredContent.
"""
