# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

UcpCapabilityUpdateRequest = TypeAliasType(
    "UcpCapabilityUpdateRequest",
    Annotated[Any, Field(..., title="UCP Capability Update Request")],
)
"""
Schema for UCP capabilities and extensions. Extensions are capabilities with an 'extends' field. Uses reverse-domain naming for governance.
"""


Extends = TypeAliasType(
    "Extends",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends25Item = TypeAliasType(
    "Extends25Item",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)


Extends25 = TypeAliasType(
    "Extends25", Annotated[list[Extends25Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends26 = TypeAliasType("Extends26", Extends)


Extends27Item = TypeAliasType("Extends27Item", Extends25Item)


Extends27 = TypeAliasType(
    "Extends27", Annotated[list[Extends27Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends28 = TypeAliasType("Extends28", Extends)


Extends29Item = TypeAliasType("Extends29Item", Extends25Item)


Extends29 = TypeAliasType(
    "Extends29", Annotated[list[Extends29Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends30 = TypeAliasType("Extends30", Extends)


Extends31Item = TypeAliasType("Extends31Item", Extends25Item)


Extends31 = TypeAliasType(
    "Extends31", Annotated[list[Extends31Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Version = TypeAliasType("Version", Any)


class Base(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends | Extends25 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class PlatformSchema(BaseModel):
    """
    Full capability declaration for platform-level discovery. Includes spec/schema URLs for agent fetching.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl = Field(..., alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends26 | Extends27 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class BusinessSchema(BaseModel):
    """
    Capability configuration for business/merchant level. May include business-specific config overrides.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends28 | Extends29 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class ResponseSchema(BaseModel):
    """
    Capability reference in responses. Only name/version required to confirm active capabilities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends30 | Extends31 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """
