# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class UcpCapability(RootModel[Any]):
    root: Any = Field(..., title="UCP Capability")
    """
    Schema for UCP capabilities and extensions. Extensions are capabilities with an 'extends' field. Uses reverse-domain naming for governance.
    """


class PlatformSchema(RootModel[Any]):
    root: Any = Field(..., title="Capability (Platform Schema)")
    """
    Full capability declaration for platform-level discovery. Includes spec/schema URLs for agent fetching.
    """


class Base(RootModel[Any]):
    root: Any


class BusinessSchema(RootModel[Base]):
    root: Base = Field(..., title="Capability (Business Schema)")
    """
    Capability configuration for business/merchant level. May include business-specific config overrides.
    """


class ResponseSchema(RootModel[Base]):
    root: Base = Field(..., title="Capability (Response Schema)")
    """
    Capability reference in responses. Only name/version required to confirm active capabilities.
    """
