# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

UcpCapability = TypeAliasType(
    "UcpCapability", Annotated[Any, Field(..., title="UCP Capability")]
)
"""
Schema for UCP capabilities and extensions. Extensions are capabilities with an 'extends' field. Uses reverse-domain naming for governance.
"""


Extends = TypeAliasType(
    "Extends",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends1Item = TypeAliasType(
    "Extends1Item",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)


Extends1 = TypeAliasType(
    "Extends1", Annotated[list[Extends1Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends2 = TypeAliasType(
    "Extends2",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends3Item = TypeAliasType(
    "Extends3Item",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)


Extends3 = TypeAliasType(
    "Extends3", Annotated[list[Extends3Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends4 = TypeAliasType(
    "Extends4",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends5Item = TypeAliasType(
    "Extends5Item",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)


Extends5 = TypeAliasType(
    "Extends5", Annotated[list[Extends5Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends6 = TypeAliasType(
    "Extends6",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Extends7Item = TypeAliasType(
    "Extends7Item",
    Annotated[
        str, Field(..., pattern="^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9_]*)+$")
    ],
)


Extends7 = TypeAliasType(
    "Extends7", Annotated[list[Extends7Item], Field(..., min_length=1)]
)
"""
Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
"""


Version = TypeAliasType("Version", Any)


class Base(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends | Extends1 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class PlatformSchema(BaseModel):
    """
    Full capability declaration for platform-level discovery. Includes spec/schema URLs for agent fetching.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl = Field(..., alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends2 | Extends3 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class BusinessSchema(BaseModel):
    """
    Capability configuration for business/merchant level. May include business-specific config overrides.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends4 | Extends5 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """


class ResponseSchema(BaseModel):
    """
    Capability reference in responses. Only name/version required to confirm active capabilities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    version: Version
    """
    Entity version in YYYY-MM-DD format.
    """
    spec: AnyUrl | None = None
    """
    URL to human-readable specification document.
    """
    schema_: AnyUrl | None = Field(None, alias="schema")
    """
    URL to JSON Schema defining this entity's structure and payloads.
    """
    id: str | None = None
    """
    Unique identifier for this entity instance. Used to disambiguate when multiple instances exist.
    """
    config: dict[str, Any] | None = None
    """
    Entity-specific configuration. Structure defined by each entity's schema.
    """
    extends: Extends6 | Extends7 | None = None
    """
    Parent capability(s) this extends. Present for extensions, absent for root capabilities. Use array for multi-parent extensions.
    """
