# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import Field, RootModel


class PaymentHandler(RootModel[Any]):
    root: Any = Field(..., title="Payment Handler")
    """
    Schema for UCP payment handlers. Handlers define how payment instruments are processed.
    """


class PlatformSchema(RootModel[Any]):
    root: Any = Field(..., title="Payment Handler (Platform Schema)")
    """
    Platform declaration for discovery profiles. May include partial config state required for discovery.
    """


class Base(RootModel[Any]):
    root: Any


class BusinessSchema(RootModel[Base]):
    root: Base = Field(..., title="Payment Handler (Business Schema)")
    """
    Business declaration for discovery profiles. May include partial config state required for discovery.
    """


class ResponseSchema(RootModel[Base]):
    root: Base = Field(..., title="Payment Handler (Response Schema)")
    """
    Handler reference in responses. May include full config state for runtime usage of the handler.
    """
