# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from .transports import embedded_config


class UcpService(RootModel[Any]):
    root: Any = Field(..., title="UCP Service")
    """
    Service binding for a specific transport. Each transport binding is a separate entry in the service array.
    """


class PlatformSchema(BaseModel):
    """
    Full service declaration for platform-level discovery. Different transports require different fields.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["rest"] = "rest"


class PlatformSchema5(BaseModel):
    """
    Full service declaration for platform-level discovery. Different transports require different fields.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["mcp"] = "mcp"


class PlatformSchema6(BaseModel):
    """
    Full service declaration for platform-level discovery. Different transports require different fields.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["a2a"] = "a2a"


class PlatformSchema7(BaseModel):
    """
    Full service declaration for platform-level discovery. Different transports require different fields.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["embedded"] = "embedded"


class PlatformSchema3(RootModel[PlatformSchema | PlatformSchema5 | PlatformSchema6 | PlatformSchema7]):
    root: PlatformSchema | PlatformSchema5 | PlatformSchema6 | PlatformSchema7 = Field(
        ..., title="Service (Platform Schema)"
    )
    """
    Full service declaration for platform-level discovery. Different transports require different fields.
    """


class BusinessSchema(BaseModel):
    """
    Service binding for business/merchant configuration. May override platform endpoints.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["rest"] = "rest"


class BusinessSchema4(BaseModel):
    """
    Service binding for business/merchant configuration. May override platform endpoints.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["mcp"] = "mcp"


class BusinessSchema5(BaseModel):
    """
    Service binding for business/merchant configuration. May override platform endpoints.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["a2a"] = "a2a"


class BusinessSchema6(BaseModel):
    """
    Service binding for business/merchant configuration. May override platform endpoints.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["embedded"] = "embedded"
    config: embedded_config.EmbeddedTransportConfig | None = None


class BusinessSchema2(RootModel[BusinessSchema | BusinessSchema4 | BusinessSchema5 | BusinessSchema6]):
    root: BusinessSchema | BusinessSchema4 | BusinessSchema5 | BusinessSchema6 = Field(
        ..., title="Service (Business Schema)"
    )
    """
    Service binding for business/merchant configuration. May override platform endpoints.
    """


class ResponseSchema(BaseModel):
    """
    Service binding in API responses. Includes per-resource transport configuration via typed config.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["rest"] = "rest"


class ResponseSchema4(BaseModel):
    """
    Service binding in API responses. Includes per-resource transport configuration via typed config.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["mcp"] = "mcp"


class ResponseSchema5(BaseModel):
    """
    Service binding in API responses. Includes per-resource transport configuration via typed config.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["a2a"] = "a2a"


class ResponseSchema6(BaseModel):
    """
    Service binding in API responses. Includes per-resource transport configuration via typed config.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    transport: Literal["embedded"] = "embedded"
    config: embedded_config.EmbeddedTransportConfig | None = None


class ResponseSchema2(RootModel[ResponseSchema | ResponseSchema4 | ResponseSchema5 | ResponseSchema6]):
    root: ResponseSchema | ResponseSchema4 | ResponseSchema5 | ResponseSchema6 = Field(
        ..., title="Service (Response Schema)"
    )
    """
    Service binding in API responses. Includes per-resource transport configuration via typed config.
    """
