# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from . import reverse_domain_name


class Instance(BaseModel):
    """
    Common fields for one outstanding Action instance are id and optional config. The extension declaring the Action type defines type-specific processing data under config. Additional properties are permitted for forward compatibility.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str = Field(..., min_length=1)
    """
    Identifier for this Action instance.
    """
    config: dict[str, Any] | None = None
    """
    Configuration defined by the extension that declares this Action type.
    """


Actions = TypeAliasType(
    "Actions",
    Annotated[
        dict[reverse_domain_name.ReverseDomainName, list[Instance]],
        Field(..., title="Actions"),
    ],
)
"""
Outstanding extension-defined Action instances, keyed by reverse-domain Action type, not extension name.
"""
