# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from typing_extensions import TypeAliasType

from . import reverse_domain_name

AmenityType = TypeAliasType(
    "AmenityType",
    Annotated[
        reverse_domain_name.ReverseDomainName,
        Field(
            ...,
            examples=[
                "dev.ucp.amenity.wi_fi",
                "dev.ucp.amenity.parking",
                "dev.ucp.amenity.shopping.in_store_pickup",
                "dev.ucp.amenity.shopping.curbside_pickup",
            ],
            title="Amenity Type",
        ),
    ],
)
"""
A standardized open reverse-DNS string representing a physical feature, capability, or service provided by a location. Supports a 2-tier hierarchy when defining well-known values in UCP: 1) Common vocabulary for universal features that directly live on `dev.ucp.amenity` (e.g., dev.ucp.amenity.wi_fi) and 2) Industry-scoped features that MUST append their related service name on top of `dev.ucp.amenity` (e.g., dev.ucp.amenity.shopping.in_store_pickup). Businesses MAY define custom vocabulary in their own domain (e.g., com.example.amenity.auto_care_center).
"""
