# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import constraint_expression


class AvailablePaymentInstrument(BaseModel):
    """
    An instrument type available from a payment handler with optional constraints.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    """
    The instrument type identifier (e.g., 'card', 'gift_card'). References an instrument schema's type constant.
    """
    constraints: constraint_expression.ConstraintExpression | None = None
    """
    A Constraint Expression describing the instrument this entry makes available. Keys in `properties` name members of the `constraint_target` declared by the instrument schema for this `type`. Requirements on submitted request data belong in `ucp.request_constraints` instead.
    """
