# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import reverse_domain_name


class Binding(BaseModel):
    """
    Binds a credential or token to a specific capability resource. Prevents reuse across different resources.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: reverse_domain_name.ReverseDomainName
    """
    The capability that owns the bound resource, for example dev.ucp.shopping.checkout. MUST be a capability name declared in the UCP namespace.
    """
    id: str = Field(..., min_length=1)
    """
    Opaque identifier of the bound resource within the owning capability, for example a checkout identifier.
    """
