# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeAliasType

from . import instrument_group

AllowedCombination = TypeAliasType(
    "AllowedCombination",
    Annotated[list[instrument_group.InstrumentGroup], Field(..., min_length=1)],
)
"""
A single valid combination: an array of instrument groups that together define the constraints. All groups must be satisfied (AND logic).
"""


class BusinessSplitPaymentsConfig(BaseModel):
    """
    Business-level configuration for split payments. Declaring the capability means multiple payment instruments are supported; this config declares which combinations are valid.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    allowed_combinations: list[AllowedCombination] = Field(..., min_length=1)
    """
    Array of valid instrument combinations. Each combination is an array of instrument groups. A payment is valid if it matches any combination.
    """
