# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing_extensions import TypeAliasType


class ValueConstraint1(BaseModel):
    """
    A Value Constraint containing `enum`, `const`, or both.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    enum: list[Any] = Field(..., min_length=1)
    """
    A non-empty array of unique JSON values.
    """
    const: Any | None = None


class ValueConstraint2(BaseModel):
    """
    A Value Constraint containing `enum`, `const`, or both.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    enum: list[Any] | None = Field(None, min_length=1)
    """
    A non-empty array of unique JSON values.
    """
    const: Any


ValueConstraint = TypeAliasType(
    "ValueConstraint", ValueConstraint1 | ValueConstraint2
)
"""
A Value Constraint containing `enum`, `const`, or both.
"""


class ConstraintExpression(BaseModel):
    """
    A closed JSON Schema Draft 2020-12 constraint expression with Object and Value Constraint positions.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    required: list[str] | None = Field(None, min_length=1)
    """
    Property names required by the constrained object. Must be non-empty: an empty array applies no constraint.
    """
    properties: dict[str, ConstraintExpression | ValueConstraint] | None = None
    """
    Constraints keyed by property name. Must be non-empty: an empty object applies no constraint.
    """
    anyOf: list[ConstraintExpression] | None = None
    """
    Alternative Object Constraints. The constrained object must satisfy at least one. A branch must be non-empty: an empty branch is satisfied by every object and neutralizes the alternation.
    """

    @field_validator("required", mode="after")
    def _enforce_unique_items_required(cls, value):  # noqa: N805
        """JSON Schema uniqueItems: reject duplicate entries."""
        if value is None:
            return value
        seen = []
        for item in value:
            if item in seen:
                raise ValueError(
                    "Items must be unique (schema uniqueItems=true)"
                )
            seen.append(item)
        return value


ConstraintExpression.model_rebuild()
