# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, model_validator


class Description(BaseModel):
    """
    Description content in one or more formats. At least one format must be provided.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    plain: str | None = None
    """
    Plain text content.
    """
    html: str | None = None
    """
    HTML-formatted content. Security: Platforms MUST sanitize before rendering—strip scripts, event handlers, and untrusted elements. Treat all rich text as untrusted input.
    """
    markdown: str | None = None
    """
    Markdown-formatted content.
    """

    @model_validator(mode="after")
    def _enforce_min_properties(self):
        """JSON Schema minProperties: require at least 1
        provided property."""
        provided = self.model_fields_set | set(self.model_extra or {})
        if len(provided) < 1:
            raise ValueError(
                "At least 1 property must be provided (schema minProperties=1)"
            )
        return self
