# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class InstrumentGroup(BaseModel):
    """
    A constraint within an allowed combination that defines which instrument types can fill this group and how many are permitted.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    types: list[str] = Field(..., min_length=1)
    """
    Instrument types accepted by this group (OR logic). Any listed type qualifies.
    """
    min: int | None = Field(0, ge=0)
    """
    Minimum number of instruments required from this group. Defaults to 0 (optional).
    """
    max: int | None = Field(1, ge=1)
    """
    Maximum number of instruments allowed from this group. Defaults to 1. MUST be greater than or equal to `min`.
    """
