# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

import re

from typing import Annotated

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
)
from typing_extensions import TypeAliasType

from . import amenity_type


class Hours(BaseModel):
    """
    Filter by operating hours, evaluated at the one supplied instant.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    open_at: AwareDatetime
    """
    The RFC 3339 instant at which matching Locations must be open, expressed with `Z` or a numeric offset. The Platform selects the instant that represents the Buyer's intent. The Business evaluates it exactly as supplied using each Location's authoritative `timezone`; the supplied offset does not identify that timezone.
    """

    @field_validator("open_at", mode="before")
    def _enforce_datetime_pattern_open_at(cls, value):  # noqa: N805
        """JSON Schema pattern: match the raw date-time string, since
        pydantic cannot apply a regex to the parsed datetime."""
        pattern = "(?:[Zz]|[+-](?:[01][0-9]|2[0-3]):[0-5][0-9])$"
        if isinstance(value, str) and re.search(pattern, value) is None:
            raise ValueError(
                f"{value!r} does not match the schema pattern {pattern}"
            )
        return value


Item = TypeAliasType("Item", Annotated[str, Field(..., min_length=1)])
"""
A non-empty, opaque Business-scoped item identifier.
"""


class LocationFilter(BaseModel):
    """
    Filter criteria to narrow Location Search and Lookup results. All supplied filters combine with AND.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    hours: Hours | None = None
    """
    Filter by operating hours, evaluated at the one supplied instant.
    """
    amenities: list[amenity_type.AmenityType] | None = None
    """
    Filter by amenity identifier. A Location matches only when its `amenities` map contains every supplied identifier as an exact key; descriptions and namespace prefixes do not participate in matching.
    """
    items: list[Item] | None = Field(None, min_length=1)
    """
    Current item-availability filter. A candidate Location matches only when the Business can currently provide every referenced item at that Location; all references combine with AND.
    """

    @field_validator("items", mode="after")
    def _enforce_unique_items_items(cls, value):  # noqa: N805
        """JSON Schema uniqueItems: reject duplicate entries."""
        if value is None:
            return value
        seen = []
        for item in value:
            if item in seen:
                raise ValueError(
                    "Items must be unique (schema uniqueItems=true)"
                )
            seen.append(item)
        return value
