# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import amenity_type, daily_hour, exception_hour
from . import geo as geo_1
from .location_summary import LocationSummary


class Amenity(BaseModel):
    """
    Buyer-facing presentation metadata for one amenity identifier. The containing map key, not this metadata, defines amenity identity and filter matching.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    description: str = Field(..., min_length=1)
    """
    Short, plain-text, buyer-facing label or phrase for the amenity, suitable for direct use in a compact list (e.g., 'Curbside pickup'). The Business SHOULD localize it for the request when possible. This content does not participate in amenity identity or filter matching.
    """


class Location(LocationSummary):
    """
    The full, rich representation of a physical business location. Builds on the Location Summary schema with discovery-centric details such as geographic coordinates, operating hours, timezone, and amenities.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    geo: geo_1.Geo | None = None
    """
    Geographic coordinates for the location.
    """
    amenities: dict[amenity_type.AmenityType, Amenity] | None = None
    """
    Static features, services, or capabilities of the Location, keyed by reverse-domain amenity identifier. Each value provides a buyer-facing description; the key alone defines amenity identity and filter matching.
    """
    hours: list[daily_hour.DailyHour] | None = None
    """
    Regular weekly operating hours whose day and time values use this Location's canonical local civil-time frame. Multiple entries for the same day support split shifts. An omitted day has no regular interval beginning that day; an interval beginning on the preceding day can carry into it. Omission of the entire `hours` property means the regular schedule is unknown.
    """
    exception_hours: list[exception_hour.ExceptionHour] | None = None
    """
    Date-specific operating-hour exceptions, including full closures, whose date and time values use this Location's canonical local civil-time frame.
    """
    timezone: str | None = None
    """
    The Business-owned IANA Time Zone Database identifier (e.g., 'America/New_York') defining this Location's canonical local civil-time frame for all returned schedule day, time, and date fields. The Business does not vary this canonical framing by the requesting Platform's or Buyer's timezone. Required when hours or exception_hours is present.
    """
