# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class LocalityCreateRequest(BaseModel):
    """
    A coarse geographic location — country, region, and postal code. A lightweight alternative to a full postal address.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    address_country: str | None = None
    """
    The country, as a 2-letter ISO 3166-1 alpha-2 code (e.g. "US"). A 3-letter alpha-3 code or full country name MAY also be used.
    """
    address_region: str | None = None
    """
    The first-level administrative region within the country (e.g. a state or province such as California).
    """
    postal_code: str | None = None
    """
    The postal code (e.g. "94043").
    """
