# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from typing_extensions import TypeAliasType

from . import (
    message_error_create_request,
    message_info_create_request,
    message_warning_create_request,
)

MessageCreateRequest = TypeAliasType(
    "MessageCreateRequest",
    Annotated[
        message_error_create_request.MessageErrorCreateRequest
        | message_warning_create_request.MessageWarningCreateRequest
        | message_info_create_request.MessageInfoCreateRequest,
        Field(..., title="Message Create Request"),
    ],
)
"""
Container for error, warning, or info messages.
"""
