# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import description as description_1
from . import payment_schedule


class PaymentTerm(BaseModel):
    """
    A way of paying for the checkout: one or more payment schedules that together cover its total.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    id: str
    """
    Unique identifier for this payment term within the checkout. Referenced by `payment.selected_term_id`.
    """
    title: str
    """
    Short label that distinguishes this term from its siblings (e.g. 'Pay now', 'Pay in 4', 'Deposit + balance at check-in').
    """
    description: description_1.Description | None = None
    """
    Supplementary context for the title (e.g. 'Save 5% by paying today'). Directly renderable; MUST NOT repeat the title.
    """
    schedules: list[payment_schedule.PaymentSchedule] = Field(..., min_length=1)
    """
    Payment schedules that settle this checkout under this term, in the order they come due.
    """
