# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator

from . import constraint_expression


class RequestConstraints(BaseModel):
    """
    Binds the shared Constraint Expression grammar to data in the next UCP request to the same resource.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    path: str | None = None
    """
    A complete RFC 9535 JSONPath query evaluated against the next logical UCP request to the same resource.
    """
    required: list[str] | None = Field(None, min_length=1)
    """
    Property names required by the constrained object. Must be non-empty: an empty array applies no constraint.
    """
    properties: (
        dict[
            str,
            constraint_expression.ConstraintExpression
            | constraint_expression.ValueConstraint,
        ]
        | None
    ) = Field(None, min_length=1)
    """
    Constraints keyed by property name. Must be non-empty: an empty object applies no constraint.
    """
    anyOf: list[constraint_expression.ConstraintExpression] | None = Field(
        None, min_length=1
    )
    """
    Alternative Object Constraints. The constrained object must satisfy at least one. A branch must be non-empty: an empty branch is satisfied by every object and neutralizes the alternation.
    """

    @field_validator("required", mode="after")
    def _enforce_unique_items_required(cls, value):  # noqa: N805
        """JSON Schema uniqueItems: reject duplicate entries."""
        if value is None:
            return value
        seen = []
        for item in value:
            if item in seen:
                raise ValueError(
                    "Items must be unique (schema uniqueItems=true)"
                )
            seen.append(item)
        return value
