# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, model_validator


class TimeInterval(BaseModel):
    """
    Reusable opening and closing time fields for a containing schedule schema. Containing schemas determine whether the `opens` and `closes` pair is required; this fragment's standalone `{}` is not an interval.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    opens: str | None = Field(None, pattern="^([01][0-9]|2[0-3]):[0-5][0-9]$")
    """
    Opening time in 24-hour HH:MM format.
    """
    closes: str | None = Field(None, pattern="^([01][0-9]|2[0-3]):[0-5][0-9]$")
    """
    Closing time in 24-hour HH:MM format.
    """

    @model_validator(mode="after")
    def _enforce_dependent_required(self):
        """JSON Schema dependentRequired: enforce dependent fields."""
        rules = {"opens": ["closes"], "closes": ["opens"]}
        provided = self.model_fields_set | set(self.model_extra or {})
        for field, required_fields in rules.items():
            if field not in provided:
                continue
            for required in required_fields:
                if required not in provided:
                    raise ValueError(
                        f"Field {required!r} is required when {field!r} "
                        "is provided (schema dependentRequired)"
                    )
        return self
